#!/usr/bin/env bash

# AgiBot
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/AgiBot/agibot_world_robot_agibot_world_beta_mobile_dual_arm_joint_absolute_position_real_s20_a20_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_22986/agibot_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/AgiBot/agibot_world_robot_agibot_world_beta_mobile_dual_arm_joint_absolute_position_real_s20_a20_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_22986/agibot_infidata/1.0.0/train

# DROID
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/DROID/droid_infidata/1.1.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/DROID/droid_infidata/1.1.0/train

# EgoVerse_full
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/EgoVerse_full/aria_bimanual_front_1/ego_verse_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/EgoVerse_full/aria_bimanual_front_1/ego_verse_infidata/1.0.0/train --state-gripper-indices "" --action-gripper-indices ""
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/EgoVerse_full/eva_bimanual_front_1_left_wrist_right_wrist/ego_verse_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/EgoVerse_full/eva_bimanual_front_1_left_wrist_right_wrist/ego_verse_infidata/1.0.0/train --state-gripper-indices "" --action-gripper-indices ""
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/EgoVerse_full/human_bimanual_front_1/ego_verse_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/EgoVerse_full/human_bimanual_front_1/ego_verse_infidata/1.0.0/train --state-gripper-indices "" --action-gripper-indices ""
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/EgoVerse_full/mecka_bimanual_front_1/ego_verse_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/EgoVerse_full/mecka_bimanual_front_1/ego_verse_infidata/1.0.0/train --state-gripper-indices "" --action-gripper-indices ""
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/EgoVerse_full/scale_front_1/ego_verse_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/EgoVerse_full/scale_front_1/ego_verse_infidata/1.0.0/train --state-gripper-indices "" --action-gripper-indices ""

# RoboCOIN
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/Agilex_Cobot_Magic_s26_a26_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_8284/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/Agilex_Cobot_Magic_s26_a26_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_8284/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/Airbot_MMK2_s36_a36_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_10532/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/Airbot_MMK2_s36_a36_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_10532/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/Galaxea_R1_Lite_s14_a14_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_3650/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/Galaxea_R1_Lite_s14_a14_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_3650/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/Realman_RMC-AIDA-L_s28_a28_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_693/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/Realman_RMC-AIDA-L_s28_a28_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_693/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/Unitree_G1_Dex3_phecda_s28_a28_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_1411/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/Unitree_G1_Dex3_phecda_s28_a28_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_1411/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/agilex_cobot_decoupled_magic_s14_a14_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_7778/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/agilex_cobot_decoupled_magic_s14_a14_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_7778/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/agilex_cobot_decoupled_magic_s14_a14_fps50_cam_high_cam_left_wrist_cam_right_wrist__episodes_3397/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/agilex_cobot_decoupled_magic_s14_a14_fps50_cam_high_cam_left_wrist_cam_right_wrist__episodes_3397/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/agilex_cobot_decoupled_magic_s26_a26_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_23712/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/agilex_cobot_decoupled_magic_s26_a26_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_23712/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/aloha_s26_a26_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_4879/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/aloha_s26_a26_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_4879/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/alpha_bot_2_s28_a28_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_857/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/alpha_bot_2_s28_a28_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_857/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/discover_robotics_aitbot_mmk2_s36_a36_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_5747/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/discover_robotics_aitbot_mmk2_s36_a36_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_5747/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/galaxea_r1_lite_s14_a14_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_5167/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/galaxea_r1_lite_s14_a14_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_5167/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/galaxea_r1_lite_s16_a18_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_970/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/galaxea_r1_lite_s16_a18_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_970/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/leju_robot_s118_a54_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_17897/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/leju_robot_s118_a54_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_17897/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/leju_robot_s54_a54_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_394/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/leju_robot_s54_a54_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_394/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/realman_rmc_aidal_s28_a28_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_18412/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/realman_rmc_aidal_s28_a28_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_18412/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/ruantong_a2d_s17_a17_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_1719/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/ruantong_a2d_s17_a17_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_1719/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/ruantong_a2d_s41_a34_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_6459/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/ruantong_a2d_s41_a34_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_6459/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/unitree_g1_s28_a28_fps30_cam_high__episodes_227/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/unitree_g1_s28_a28_fps30_cam_high__episodes_227/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/unitree_g1_s28_a28_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_931/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/unitree_g1_s28_a28_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_931/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/unknown_s30_a30_fps30_cam_high__episodes_891/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/unknown_s30_a30_fps30_cam_high__episodes_891/robocoin_infidata/1.0.0/train
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboCOIN/yinhe_s49_a16_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_5452/robocoin_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboCOIN/yinhe_s49_a16_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_5452/robocoin_infidata/1.0.0/train


# RoboMIND_full
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboMIND_full/agilex_cobot_magic_agilex_dual_arm_h5_agilex_3rgb_real_s14_a14_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_10374/robomind_full_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboMIND_full/agilex_cobot_magic_agilex_dual_arm_h5_agilex_3rgb_real_s14_a14_fps30_cam_high_cam_left_wrist_cam_right_wrist__episodes_10374/robomind_full_infidata/1.0.0/train --state-gripper-indices "6,13" --action-gripper-indices "6,13"
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboMIND_full/franka_fr3_dual_master_puppet_joint_position_h5_franka_fr3_dual_real_s16_a16_fps30_cam_high_cam_left_cam_right_cam_top__episodes_1774/robomind_full_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboMIND_full/franka_fr3_dual_master_puppet_joint_position_h5_franka_fr3_dual_real_s16_a16_fps30_cam_high_cam_left_cam_right_cam_top__episodes_1774/robomind_full_infidata/1.0.0/train --state-gripper-indices "7,15" --action-gripper-indices "7,15"
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboMIND_full/franka_panda_master_puppet_joint_position_h5_franka_3rgb_real_s8_a8_fps30_cam_left_cam_right_cam_top__episodes_17219/robomind_full_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboMIND_full/franka_panda_master_puppet_joint_position_h5_franka_3rgb_real_s8_a8_fps30_cam_left_cam_right_cam_top__episodes_17219/robomind_full_infidata/1.0.0/train --state-gripper-indices "7" --action-gripper-indices "7"
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboMIND_full/franka_sim_simulation_franka_joint_position_h5_sim_franka_3rgb_sim_s8_a8_fps30_cam_front_external_cam_handeye_cam_left_external_cam_right_external__episodes_14488/robomind_full_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboMIND_full/franka_sim_simulation_franka_joint_position_h5_sim_franka_3rgb_sim_s8_a8_fps30_cam_front_external_cam_handeye_cam_left_external_cam_right_external__episodes_14488/robomind_full_infidata/1.0.0/train --state-gripper-indices "7" --action-gripper-indices "7"
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboMIND_full/franka_sim_simulation_franka_joint_position_h5_simulation_sim_s8_a8_fps30_cam_front_external_cam_handeye_cam_left_external_cam_right_external__episodes_11422/robomind_full_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboMIND_full/franka_sim_simulation_franka_joint_position_h5_simulation_sim_s8_a8_fps30_cam_front_external_cam_handeye_cam_left_external_cam_right_external__episodes_11422/robomind_full_infidata/1.0.0/train --state-gripper-indices "7" --action-gripper-indices "7"
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboMIND_full/franka_sim_simulation_franka_joint_position_h5_simulation_sim_s8_a8_fps30_cam_handeye_cam_left_external_cam_right_external__episodes_158/robomind_full_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboMIND_full/franka_sim_simulation_franka_joint_position_h5_simulation_sim_s8_a8_fps30_cam_handeye_cam_left_external_cam_right_external__episodes_158/robomind_full_infidata/1.0.0/train --state-gripper-indices "7" --action-gripper-indices "7"
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboMIND_full/franka_sim_simulation_franka_joint_position_none_sim_s8_a8_fps30_cam_front_external_cam_handeye_cam_left_external_cam_right_external__episodes_222/robomind_full_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboMIND_full/franka_sim_simulation_franka_joint_position_none_sim_s8_a8_fps30_cam_front_external_cam_handeye_cam_left_external_cam_right_external__episodes_222/robomind_full_infidata/1.0.0/train --state-gripper-indices "7" --action-gripper-indices "7"
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboMIND_full/tienkung_humanoid_master_puppet_joint_position_h5_tienkung_gello_1rgb_real_s16_a16_fps30_cam_top__episodes_6626/robomind_full_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboMIND_full/tienkung_humanoid_master_puppet_joint_position_h5_tienkung_gello_1rgb_real_s16_a16_fps30_cam_top__episodes_6626/robomind_full_infidata/1.0.0/train --state-gripper-indices "7,15" --action-gripper-indices "7,15"
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboMIND_full/tienkung_humanoid_master_puppet_joint_position_h5_tienkung_prod1_gello_1rgb_real_s16_a16_fps30_cam_top__episodes_2959/robomind_full_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboMIND_full/tienkung_humanoid_master_puppet_joint_position_h5_tienkung_prod1_gello_1rgb_real_s16_a16_fps30_cam_top__episodes_2959/robomind_full_infidata/1.0.0/train --state-gripper-indices "7,15" --action-gripper-indices "7,15"
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboMIND_full/tienkung_humanoid_master_puppet_joint_position_h5_tienkung_xsens_1rgb_real_s14_a14_fps30_cam_top__episodes_6126/robomind_full_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboMIND_full/tienkung_humanoid_master_puppet_joint_position_h5_tienkung_xsens_1rgb_real_s14_a14_fps30_cam_top__episodes_6126/robomind_full_infidata/1.0.0/train --state-gripper-indices "" --action-gripper-indices ""
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboMIND_full/tienkung_humanoid_tiangong_joint_position_h5_sim_tienkung_1rgb_sim_s38_a38_fps30_cam_chest_cam_head__episodes_3965/robomind_full_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboMIND_full/tienkung_humanoid_tiangong_joint_position_h5_sim_tienkung_1rgb_sim_s38_a38_fps30_cam_chest_cam_head__episodes_3965/robomind_full_infidata/1.0.0/train --state-gripper-indices "" --action-gripper-indices ""
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboMIND_full/tienkung_humanoid_tiangong_joint_position_none_real_s38_a38_fps30_cam_chest_cam_head__episodes_146/robomind_full_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboMIND_full/tienkung_humanoid_tiangong_joint_position_none_real_s38_a38_fps30_cam_chest_cam_head__episodes_146/robomind_full_infidata/1.0.0/train --state-gripper-indices "" --action-gripper-indices ""
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/RoboMIND_full/ur5e_master_puppet_joint_position_h5_ur_1rgb_real_s7_a7_fps30_cam_top__episodes_26380/robomind_full_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/RoboMIND_full/ur5e_master_puppet_joint_position_h5_ur_1rgb_real_s7_a7_fps30_cam_top__episodes_26380/robomind_full_infidata/1.0.0/train --state-gripper-indices "6" --action-gripper-indices "6"

# realworld_piper_task_split
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/realworld_piper_task_split/piper_s14_a14_fps30_c4_ee_pose_cam_front_cam_high_cam_left_wrist_cam_right_wrist/realworld_piper_infidata/1.1.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/realworld_piper_task_split/piper_s14_a14_fps30_c4_ee_pose_cam_front_cam_high_cam_left_wrist_cam_right_wrist/realworld_piper_infidata/1.1.0/train

# realworld_piper_2
/data/wudi/.venvs/infidata-quality/bin/python /data/wudi/InfiData-personal/scripts/quality/filter_rlds_state_action.py --dataset-dir /data/wudi/RLDS/realworld_piper_2/realworld_piper_infidata/1.0.0 --split train --output-dir /data/wudi/InfiData-personal/quality_runs/all_rlds/realworld_piper_2/realworld_piper_infidata/1.0.0/train
